# Generated by Django 6.0 on 2025-12-26 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_location", models.CharField(max_length=255)),
                (
                    "start_lat",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "start_lon",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                ("end_location", models.CharField(max_length=255)),
                (
                    "end_lat",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "end_lon",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                ("total_distance", models.FloatField()),
                ("route_data", models.JSONField(default=dict)),
                (
                    "vehicle_mpg",
                    models.FloatField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "fuel_price_per_gallon",
                    models.FloatField(
                        default=3.5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("total_fuel_cost", models.FloatField()),
                ("gallons_needed", models.FloatField()),
                ("fuel_stops", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
